# Generated by Django 4.2.6 on 2023-10-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('deal_id', models.AutoField(primary_key=True, serialize=False)),
                ('deal_name', models.CharField(default='Default Name', max_length=255)),
                ('stage', models.CharField(default='Default Stage', max_length=255)),
                ('activity', models.CharField(default='Default Activity', max_length=255)),
                ('client', models.CharField(default='Default Client', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('responsible', models.CharField(default='Default Responsible', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer_journey', models.CharField(default='Default Journey', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_score', models.IntegerField(blank=True, null=True)),
                ('lead_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('lead_source', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_type', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('authority', models.CharField(blank=True, max_length=255, null=True)),
                ('need', models.TextField(blank=True, null=True)),
                ('timeline', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
