# Generated by Django 4.2.6 on 2023-10-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antcrm', '0002_lead_delete_leads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lead',
            new_name='Leads',
        ),
    ]
